import { Column, Entity, PrimaryColumn, PrimaryGeneratedColumn } from 'typeorm';

@Entity('users')
export class User {
  @PrimaryGeneratedColumn() //automatically generated by mySql
  id: number;

  @Column()
  name: string;
  @Column({ unique: true })
  email: string;
  @Column()
  password: string;
}
